spring:
    tomcat:
      initialSize: 10
      maxActive: 300
      minIdle: 10
      maxIdle: 20
      testWhileIdle: true
      testOnBorrow: true
      validationQuery: SELECT 1
      validationInterval: 30000
      validationQueryTimeout: 5
      timeBetweenEvictionRunsMillis: 1800000
      maxWait: 10000
      removeAbandonedTimeout: 60
      minEvictableIdleTimeMillis: 30000
      initSQL: set names utf8mb4
      maxAge: 14400000